### ISSUE TITLE
Plan for handling customization of new repositories.

### ISSUE THREAD

**Issue by georgestephanis** [a8cteam51/team51-cli#2]
Previously, the team51-cli client would create a local clone of the new repository on the user's computer, do the find/replace there, and then push the code up to the repository.  This is somewhat fragile, depends on an authenticated git setup between the computer's command line and github, and is kind of out-of-keeping with the thin-client concepts we're working to migrate toward.

So, for this iteration, my intent is to migrate the operation to a GitHub Action.

I'm planning on doing this in several steps:

- [x] 1. Register [GitHub Repository Custom Properties](https://docs.github.com/en/organizations/managing-organization-settings/managing-custom-properties-for-repositories-in-your-organization) in our a8cteam51 organization to store the values we'll be interpolating. Determine a list of the custom properties we'll be potentially using for repositories.  This will have an ancillary benefit in that the properties used at creation can also be subsequently used organizationally when we're managing repositories -- to sort, filter, etc.
- [x] 2. The properties can be populated at repository creation via the `custom_properties` parameter, [as documented in the repository creation endpoint](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository).
- [x] 3. Build a workflow into the plugin/theme/issue/project scaffold that will do a find/replace -- either simple string swaps, or mustache templates, or any other method -- and update the repository's code.  Prior Art: [.yml](https://github.com/ImLunaHey/ts-template/blob/main/.github/workflows/templating.yml) [.mjs](https://github.com/ImLunaHey/ts-template/blob/main/.github/workflows/templating.mjs)
- [x] 4. Once the repository is created, we can [use the github api to create a Workflow Dispatch Event](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) to fire the GitHub Action.  Requiring it to be fired like this manually means it won't need to be listening forever to other potential conditions.  We could also do a [Repository Dispatch event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) instead -- honestly there's several ways it could be triggered, I'm not going to fret overly much right now about which we wind up using.

This is a workflow that will work for us as we're creating new repositories generally staying in our own organization -- where the custom repo properties would be defined.  If others wanted to use this, they may need to also define those properties as well, or create their own scaffolding with their own properties to interpolate.

**Comment by georgestephanis** [comment]
Fields I'm evaluating registering -- about to check the scaffolds and see if any of them wind up being duplicated -- like `site-php-short-prefix` and `plugin-php-short-prefix` to see if they could be consolidated to one, or if any of them aught be dropped.  I figure the slug is probably accessible to gh actions without needing to be a property on itself, for example.

```
'repo-slug' // Repository name in slug form (e.g. client-name).
'repo-description' // A short, human-friendly description for this project.
'repo-type' // The type of repository. One of either `project`, `plugin`, or `issues`.

// region PROJECT REPO OPTIONS
'site-production-url' // The hostname of the intended production site (do not include http/https, e.g. example.com).
'site-development-url' // The hostname of the intended development site (do not include http/https, e.g. development-example.com).
'site-php-long-prefix' // The long prefix for global PHP variables inside the project.
'site-php-short-prefix' // The short prefix for global PHP variables inside the project.

// region PLUGIN REPO OPTIONS
'plugin-name' // The name of the plugin.
'plugin-php-short-prefix' // 'The short prefix for global PHP variables inside the plugin.

// region LEGACY OPTIONS
'issue-repo-only' // Is this a repository to track project issues only with no associated code?
'production-url' // The hostname of the intended production site (do not include http/https, e.g. example.com).
'development-url' // The hostname of the intended development site (do not include http/https, e.g. development-example.com).
'custom-theme-slug' // If this project involves us building a custom WordPress theme, this is the slug of the theme.
'custom-plugin-slug' // If this project involves us building a custom WordPress plugin, this is the slug of the plugin.
```

**Comment by georgestephanis** [comment]
noting that in actions, the custom properties are gettable via `github.event.repository.custom_properties`

https://github.com/orgs/community/discussions/69914#discussioncomment-7441108

**Comment by georgestephanis** [comment]
Got this in a `meetup/scaffold-population` branch here:

https://github.com/a8cteam51/team51-project-scaffold/commit/a501c6e11649df7150d9657973f8218f99a4c29b

From what Tony mentioned earlier, I'm intending on pruning it down as it goes into each scaffold -- projects, plugins, issues -- so there's fewer conditionals in each, as it's more fit-to-purpose with less dead code paths.

The custom properties have been created for the organization and can be populated on repositories -- for example:

https://github.com/a8cteam51/torrent-meetup-test-georgestephanis/settings/custom-properties

<img width="823" alt="Screenshot 2024-04-09 at 5 12 34 PM" src="https://github.com/a8cteam51/team51-cli/assets/941023/8e2516fa-1b3d-41a6-a2cd-0bdbfd395e31">

Next steps are to get the thincli command to include the parameters to populate these, which will register them on the new repository, and then to add an invocation so that it will trigger the workflow to run which will interpolate them after the scaffold template has been duplicated into the new repository.

And then re-read the prior code to see if there's anything else that need to be duplicated like creation of tags and such or the like.

**Comment by georgestephanis** [comment]
pr created to track opsoasis hub functionality to push data to the new repository once created, and then trigger the action workflow to swap in the templating.

https://github.com/a8cteam51/opsoasis/pull/22

**Comment by georgestephanis** [comment]
to do yet: a pr for the thinclient that will collect the right properties and send them up to the hub.

**Comment by georgestephanis** [comment]
Also, should we do a `title` property for the project that's human readable for the readme and such, distinct from the repo slug?

**Comment by ahegyes** [comment]
This has been merged on all issues repos, and both the CLI and OpsOasis have been updated to support this workflow.
