### ISSUE TITLE
Complete and migrate `pattern-export-to-repo` command

### ISSUE THREAD

**Issue by GeoJunkie** [a8cteam51/team51-cli#6]
A new `pattern-export-to-repo` command is being added to the legacy Team 51 CLI: https://github.com/Automattic/team51-cli/issues/220

This command will also need to be migrated to this CLI.

**Comment by ahegyes** [comment]
https://github.com/Automattic/team51-cli/issues/220

**Comment by GeoJunkie** [comment]
Since it makes more sense to complete the command during the migration, rather than implement it on the deprecated CLI, I'm adding the details from Automattic/team51-cli#220 here:

Context: p4Kr4c-cMG-p2

The team51 pattern-export-to-repo was being built in this branch https://github.com/Automattic/team51-cli/tree/add/pattern-export

Before launching, the command needs to replace any images within the patterns with the equivalent sized image from [Placehold](https://placehold.co/).
